# Generated by Django 5.1 on 2024-08-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('doors_nk', models.IntegerField(default=0)),
                ('doors_sk', models.IntegerField(default=0)),
                ('doors_2nk', models.IntegerField(default=0)),
                ('doors_2sk', models.IntegerField(default=0)),
                ('hatches_nk', models.IntegerField(default=0)),
                ('hatches_sk', models.IntegerField(default=0)),
                ('gates', models.IntegerField(default=0)),
                ('glass_order', models.JSONField(default=dict)),
            ],
        ),
    ]
