# Generated by Django 5.1 on 2024-08-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vent',
            field=models.IntegerField(default=0),
        ),
    ]
